version: "3"

services:
    app:
        build: 
            context: .
        ports:
            - "8123:8000"
        volumes: 
            - ./app:/app
        command: >
            sh -c "python manage.py runserver 0.0.0.0:8123"